spring:
  application:
    name: ${APP_NAME:manager-travel}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}          # create-drop, update, validate, none?
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
